include:
  - local: .gitlab/ci/workflow.yml
  - local: .gitlab/ci/validate.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/build.yml
  - local: .gitlab/ci/security.yml
  - local: .gitlab/ci/deploy-staging.yml
  - local: .gitlab/ci/rollback.yml
