apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: nav.local
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  name: http
